services:
  db:
    image: mariadb:10.6
    env_file: .env
    volumes:
      - ./storage/db:/var/lib/mysql

  espocrm:
    image: espocrm/espocrm:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./storage/espocrm:/var/www/html
    depends_on:
      - db

  gateway-api:
    build: ./api
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - espocrm